### PR TITLE
CentOS support added

### PR DESCRIPTION
**Pull request by zskulcsar**
Hi Kevin,
added CentOS support to the role, kindly review and approve.

### CODE REVIEW

**Comment by kbrebanov** [comment]
@zskulcsar I'm still debating merging this or not. If I do merge it, I would also have to test against CentOS 6 & 7 when I make changes and I don't really use those distros currently.

**Comment by zskulcsar** [comment]
@kbrebanov If that helps, I'm more than happy to do some testing for you

**Comment by kbrebanov** [comment]
@zskulcsar Thanks for the offer, but I think it would be better to try and modify the Travis configuration, maybe using their docker service, to enable automatically testing multiple distros. Problem is, right now, I'm pretty busy with other stuff...

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.

**Pull request closed without merging**
